### ISSUE TITLE
DayEntry Started At and Ended At

### ISSUE THREAD

**Issue by rudgr** [ithielnor/harvest.net#22]
Seems DayEntry.StartedAt en EndedAt output DateTime.Now as the Date part of the DateTime instead of the actual Date the entry was tracked?

**Comment by ithielnor** [comment]
Which resource are you using? Can you provide some code to reproduce?

**Comment by rudgr** [comment]
sorry, didn't see the notifications.. I'm using: Client.ListUserEntries(...)

**Comment by ithielnor** [comment]
Sorry I didn't get around to this sooner. 

https://github.com/ithielnor/harvest.net/blob/master/Harvest.Net/Models/DayEntry.cs#L37

The `StartedAt` and `EndedAt` values are only set when you use the Daily resource (i.e. `Client.Daily(...)`)

If you want the date of the entry, you should use `SpentAt`.

I will add documentation to these properties to help avoid confusion.

**Comment by rudgr** [comment]
great, tx!
