### ISSUE TITLE
ListProjects() is returning NULL

### ISSUE THREAD

**Issue by marioharper** [ithielnor/harvest.net#23]
The xml is getting returned properly from the API, however, the T Execute<T> method in HarvestRestClient.cs  is not returning any data for projects. Is there something off with the serialization?

**Comment by versaielle** [comment]
It seems to the serialization to me.. resp.Content = resp.Content.TrimStart(byteOrderMarkUtf8.ToArray()

is not plugging anything in .data

**Comment by marioharper** [comment]
I'm thinking it may be due to this issue I logged for the api:  https://github.com/harvesthq/api/issues/120 
Will retest once the issue is resolved.

**Comment by ithielnor** [comment]
Maybe, but I think we use XML exclusively since I found too many inconsistencies in Harvest's json responses. I don't think we request `application/json` anywhere.

**Comment by amosp** [comment]
I used Fiddler to view the request and response. The library requests xml "Accept: application/xml, text/xml" and the received data reports itself as json even though xml was requested and that's the format received "Content-Type: application/json; charset=utf-8".

**Comment by hbgwhite** [comment]
HarvestXmlDeserializer Deserialize<T>(IRestResponse response) is not being called for this project call.

**Comment by hbgwhite** [comment]
Here is my hack-tastic solution:

 // Harvest API is inconsistent in JSON responses so we'll stick to XML
            _client.ClearHandlers();
            _client.AddHandler("application/xml", new HarvestXmlDeserializer());
            _client.AddHandler("text/xml", new HarvestXmlDeserializer()); 
            _client.AddHandler("application/json", new HarvestXmlDeserializer());

Since the harvest API is returning body xml but application/json as the header content type, I've set the application/json handler to the XmlDeserializer. The other responses that  faithfully represent their content types should be unaffected. I'm going to post a bug to the Harvest API people.

**Comment by ithielnor** [comment]
It's definitely sub optimal, but as long as their api is serving it wrong I guess we can do that. 

Submit a PR and I'll get this up on Nuget.

**Comment by ithielnor** [comment]
Jonathan says it is fixed: https://github.com/harvesthq/api/issues/120#issuecomment-97552573

Test and let me know if we still need a patch.

**Comment by marioharper** [comment]
Retested, its working properly now. Thanks.
