### ISSUE TITLE
Problem with CreateDaily

### ISSUE THREAD

**Issue by hbgwhite** [ithielnor/harvest.net#24]
I'm getting exceptions trying to use CreateDaily. The same parameters sent directly against the API using DHC work fine and return a 201:

<request>
  <notes>Test api support</notes>
  <hours>1</hours>
  <project_id type="integer">7925148</project_id>
  <task_id type="integer">4218975</task_id>
  <spent_at type="date">5/1/2015 12:00:00 AM</spent_at>
</request>

I'm going to download the project and try to debug the issue. If anyone has any insight of workarounds please let me know!

**Comment by hbgwhite** [comment]
The problem is the create daily method when writing to user's timesheets other than your own. The method attempts to include the "of_user" parameter in the body of the POST, but the API requires this parameter in the URL.

Here's a working version:

var request = Request(ofUser != null ? string.Format("daily/add?of_user={0}", ofUser) : "daily/add", RestSharp.Method.POST);

**Comment by hbgwhite** [comment]
I've submitted a pull request with this fix.

**Comment by ithielnor** [comment]
Fixed by #25
