### ISSUE TITLE
ListProjects returning null

### ISSUE THREAD

**Issue by hbgwhite** [ithielnor/harvest.net#26]
The ListProjects call is returning a 200 status code, but null data. I've tested on DHC hitting the Harvest API directly and it's returning results.

**Comment by ithielnor** [comment]
Is it related to this: https://github.com/ithielnor/harvest.net/issues/23 ?

I've not tested, but folks said this was fixed.

**Comment by ithielnor** [comment]
Is this some re-emergence of #23?

**Comment by hbgwhite** [comment]
It doesn't look like the same issue; The data is being returned with the correct content type this time.

**Comment by ithielnor** [comment]
`ListProjects_Returns` is succeeding on my test account. Can you run it with your credentials?

**Comment by hbgwhite** [comment]
ListProjects is working when provided with client ID, but failing without one. I just ran the test and it works fine on your test account (returning 2 projects), but fails with my credentials.

![image](https://cloud.githubusercontent.com/assets/1069704/7601367/d7b3fcba-f8c9-11e4-9592-9d5965d56e1e.png)

I'll keep investigating. Maybe this problem is isolated to my account. I'll try it with another admin's credentials.

**Comment by ithielnor** [comment]
Just ran it on my production account and it worked. It's probably account related. 

Harvest likes to make little undocumented changes every now and then. I'd try commenting out segments of the Project model and see if you can figure out what's different about your account.

**Comment by hbgwhite** [comment]
Thanks @ithielnor, I'll keep working through it.

**Comment by luciusism** [comment]
@ithielnor, I noticed that if any of my projects has the budget option turned on, then none of the projects will be returned. If I turn the budget option off, then ListProjects() will work again.

**Comment by luciusism** [comment]
@ithielnor, debugging the code, the error is generated at HarvestXmlDeserializer.Map, prop.SetValue(x, type.FindEnumValue(value.ToString(), Culture), null);

Specifically, it's throwing "Input string was not in a correct format" error when trying to set project.EstimateBy member with enum value, EstimateMethod.

**Comment by ithielnor** [comment]
Thanks for the updates, @luciusism. I'll try to repro and fix this weekend.

**Comment by ithielnor** [comment]
`EstimateMethod` does not appear to be used by Harvest. The only enum value we have is `None`. I've fixed the `BudgetMethod` as per @luciusism's other ticket. 

Also discovered a bug in `UpdateProject` while testing it. Apparently `clientId` is a required field for updates.
