### ISSUE TITLE
Execute Exception Handling

### ISSUE THREAD

**Issue by luciusism** [ithielnor/harvest.net#29]
For the HarvestRestClient.Execute method, when response.StatusCode == System.Net.HttpStatusCode.BadRequest, I suggest throwing the response.Content which includes Harvest's error message.

**Comment by ithielnor** [comment]
Isn't this what we are currently doing? I'll have to look back at this, as I thought I had implemented that.

**Comment by ithielnor** [comment]
Looks like I was only throwing the headers. I've added the content for the next rev.

**Comment by ithielnor** [comment]
I've created a new `HarvestException` class which exposes the IRestResponse object directly.
