### ISSUE TITLE
ListProjectEntries returning null - issue with access_token

### ISSUE THREAD

**Issue by synewaves** [ithielnor/harvest.net#32]
I'm getting nulls when calling `ListProjectEntries` and using OAuth2 authentication.  Looks like the issue is the way the URL is constructed when using OAuth2.  Using Fiddler, I can see that the call returns a 401 error from Harvest with the following data:

`{"error":"invalid_token","error_description":"The access token provided is expired, revoked, malformed or invalid for other reasons."}`

The URL that gets generated for the call seems to be incorrect.  The access_token parameter adds a second `?` to the URL; example below (from Fiddler, edited to remove token):

`/projects/removedprojectid/entries?access_token=removedaccesstoken?from=20150801&to=20150831`

As you can see, there two `?` in the constructed URL.  Removing the second question mark and calling manually does work.

**Comment by ithielnor** [comment]
Released 0.14.1
