### ISSUE TITLE
Model Documentation

### ISSUE THREAD

**Issue by ithielnor** [ithielnor/harvest.net#39]
Need to go through all the classes in `/models` and provide basic documentation.

Documentation can mostly be copy-pasted from http://help.getharvest.com/api/

**Comment by mamonu** [comment]
hey! forked harvest.net ... What kind of documentation are you looking for? 
(had a look on the api pages you linked)
ie comments? html page? a text file?

Just need to understand what and I am on it

**Comment by ithielnor** [comment]
Hey thanks! Would love property summary comments in code.

**Comment by igeligel** [comment]
Hi, probably you have noticed that i am working on documentation of the models right now. Do you wish daily pull requests or one big when i am done (probably cant do it all).

**Comment by ithielnor** [comment]
Whichever works best for you!

**Comment by igeligel** [comment]
I have done the pull requests for all models [here](https://github.com/ithielnor/harvest.net/pull/58).
