### ISSUE TITLE
ListClients is returning null

### ISSUE THREAD

**Issue by fargs** [ithielnor/harvest.net#40]
Hi,

When I call client.ListClients() it is always returning a null value.
I have fiddler running and when the method is executed it is sending the request and responding with a list of clients in xml format.

client.ListProjects works fine. It returns a populated list of Projects. In Fiddler the request headers look exactly the same and both are returning xml.

Any ideas?

Thanks!

**Comment by ithielnor** [comment]
Can you copy one of the client nodes from the response xml here? Feel free to sanitize it. I'm mostly looking for the enumeration values and property names. Quite often Harvest changes something without documenting it ahead of time.

**Comment by fargs** [comment]
Here you go.

```xml
<client>
    <id type="integer">000000</id>
    <name>-OTHER</name>
    <active type="boolean">true</active>
    <currency>Canadian Dollar - CAD</currency>
    <highrise-id type="integer" nil="true"/>
    <cache-version type="integer">0000000000</cache-version>
    <updated-at type="dateTime">2015-09-23T17:16:07Z</updated-at>
    <created-at type="dateTime">2015-09-23T17:16:07Z</created-at>
    <statement-key>{someguid}</statement-key>
    <currency-symbol>$</currency-symbol>
    <details></details>
    <default-invoice-timeframe nil="true"/>
    <last-invoice-kind nil="true"/>
</client>
```

**Comment by ithielnor** [comment]
Looks like "Canadian Dollar - CAD" used to be "Canada Dollar - CAD". 

I'm not sure why Harvest can't standardize and quit messing with these, or just use the acronym. We may want to modify Harvest.Net to try and be more robust around this enumeration. It's happened a number of times now.
