### ISSUE TITLE
.ListProjects() returning null

### ISSUE THREAD

**Issue by CamronBute** [ithielnor/harvest.net#42]
Running this:

    var client = new HarvestRestClient("subdomain", "user.name@domain.com", "password");
    return client.ListProjects();

is returning null.

**Comment by CamronBute** [comment]
Upon inspection, it seems that OverBudgetNotificationPercentage is coming across as "" in our instance of Harvest (not in your test instance,though), and then on line 208 of HarvestXmlDeserializer, it tries to cast the decimal, but it fails, which results ultimately in no data being returned.

**Comment by ithielnor** [comment]
Fixed by PR #43
