### ISSUE TITLE
NuGet package is not signed

### ISSUE THREAD

**Issue by CamronBute** [ithielnor/harvest.net#44]
Because the .dll in the NuGet package isn't signed, it's a real pain to try and use it when I need signing.

It seems that the only package dependency is RestSharp, and they maintain a signed version of their package with the name RestSharpSigned.

I would love to see this implemented!

**Comment by ithielnor** [comment]
Good idea. I've not signed a package before. I'll have to look into that.

**Comment by paulirwin** [comment]
-1. Strong naming needs to go away. If you've never experienced Binding Redirect hell, it is an absolutely terrible experience. But, if you can't self-sign it, then an alternate signed version is okay. Just please, please, do not sign the main NuGet release.

**Comment by ithielnor** [comment]
Yeah, I was just reading up on this in restsharp's repo. Their signed version is a community maintained project. 

Seems like the limitations of strong naming are rather egregious. I don't think I can overcome them to properly maintain a strong named version. If someone else would like to branch off and maintain a separate project for that I'll be happy to link it from the readme. For now I think it is outside the scope of this effort.
