### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by paulirwin** [ithielnor/harvest.net#47]
It would be great to have Async versions of all API methods that return `Task`/`Task<T>`  to support `async` and `await`. RestSharp already supports this so it wouldn't be much work. Would likely involve a little refactoring so that the Async methods aren't full duplicates of the synchronous methods.

I'd be happy to work on this, as I have done this for other projects.

**Comment by ithielnor** [comment]
I like the idea. I think the synchronous methods should be wrappers of the async methods, correct?

**Comment by paulirwin** [comment]
That's one way of doing it, but sometimes you can run into issues around the synchronization context. Further reading: http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx

My usual recommendation would be to refactor out the code as much as possible for re-use, but keep the sync/async call stacks separate. But, we could do ConfigureAwait(false) too if RestSharp doesn't deadlock from using it.

**Comment by paulirwin** [comment]
Here is my first pass at refactoring to support async, with just Account and Client methods done so far. Let me know if this is along the lines of something that you'd be okay with before I get too much farther. 

https://github.com/paulirwin/harvest.net/commit/de2e28a78708336964dd364580aaf580c0fb414e

**Comment by ithielnor** [comment]
Sorry for letting this drop. 

Your approach looks fine by me.

**Comment by paulirwin** [comment]
Cool, working on this now.

**Comment by Willjobs94** [comment]
Hey @paulirwin I would like to know how is the Async thing going ?

**Comment by paulirwin** [comment]
@Willjobs94 Unfortunately I completely stopped work on it and forgot about it. Thanks for reminding me! My progress is here: https://github.com/paulirwin/harvest.net/tree/feature/async

If anyone wants to help me out that would be awesome.

**Comment by paulirwin** [comment]
PR #75 submitted today, 21 months later. Better late than never?
