### ISSUE TITLE
Update DailyOptions Model

### ISSUE THREAD

**Issue by ThomasKur** [ithielnor/harvest.net#51]
At the Moment it's not possible to approve or mark a time entry as invoiced. According to the following page (http://help.getharvest.com/api/timesheets-api/timesheets/adding-updating-time/), it should be a really small change: to the UpdateDaily Method and DailyOptions Model. 

Can you add that  functionality?

**Comment by ithielnor** [comment]
I'm looking at that page and it looks like it the update method only supports the following fields:

```
<request>
  <notes>New notes.</notes>
  <hours>1.07</hours>
  <spent_at type="date">Tue, 17 Oct 2016</spent_at>
  <project_id>52234</project_id>
  <task_id>67567</task_id>
</request>
```

We already have all these in the DailyOptions class
