### ISSUE TITLE
Throw a HarvestException for any 4xx or 5xx HTTP status code

### ISSUE THREAD

**Issue by paulirwin** [ithielnor/harvest.net#54]
Currently the HarvestRestClient only throws a HarvestException if the status code is 400 Bad Request. In the event of a different error status code, such as 503 if you've been [rate limited](http://help.getharvest.com/api/introduction/overview/introduction/#throttle-limit---http-503) or perhaps an unexpected 500 server error, the method just returns null and doesn't let the calling code know about the reason for the failure.

I'm submitting a PR for this shortly.

**Comment by paulirwin** [comment]
Note that this is effectively a breaking change - code expecting the return value to be `null` on error will now get an exception instead. This should bump the version to 0.16 or greater.

**Comment by ithielnor** [comment]
Agreed
