### ISSUE TITLE
C# 6 support?

### ISSUE THREAD

**Issue by paulirwin** [ithielnor/harvest.net#56]
I'm working on the async changes from #47 and I'm wondering if it's okay to use C# 6 features, primarily string interpolation and the nameof operator. This would require the project to be built with VS2015.

**Comment by ithielnor** [comment]
I'm good with that. VS 15 is about to release, so anyone who wants to touch this code should be at least at VS2015

**Comment by paulirwin** [comment]
Sounds good, thanks!
