### ISSUE TITLE
Add Resource methods to IHarvestRestClient to allow for Mocking of HarvestRestClient for testing.

### ISSUE THREAD

**Issue by BenJBailey** [ithielnor/harvest.net#60]
Currently there are only a handful of methods available in the `IHarvestRestClient`. In order to write tests and mock the `HarvestRestClient` methods using a framework like [MOQ](https://github.com/moq/moq4), the Resource methods need to be included in the interface. This would allow for easier testing using this library.

**Comment by ithielnor** [comment]
Will include in next release.
