### ISSUE TITLE
AUD/USD Currency on getClients()

### ISSUE THREAD

**Issue by gavinbenda** [ithielnor/harvest.net#62]
Having a few issues with clients who are set to non-USD currencies.
Nothing is returned when the client is set to AUD, but it returns the results fine when clients are set to USD.
Any tips or tricks around this?
Thanks!

**Comment by ithielnor** [comment]
See issue #41. Currently we use string comparison on description to deserialize enums. Harvest seems to like to change the descriptions of the currency values.

Can you send me a sample response with AUD to confirm this is the issue?

**Comment by gavinbenda** [comment]
Thanks for that! Here's an example of the data returned via Postman.
Anytime any client is stored in AUD, it will cause the wrapper to return a null object on getClients().

`[
  {
    "client": {
      "id": XXXXXXXX,
      "name": "Test Client",
      "active": true,
      "currency": "United States Dollar - USD",
      "highrise_id": null,
      "updated_at": "2016-12-07T11:19:38Z",
      "created_at": "2016-12-07T10:45:29Z",
      "statement_key": "3c8d77c01213935b8b66579e9fe31fce",
      "default_invoice_kind": null,
      "default_invoice_timeframe": null,
      "address": "",
      "cache_version": 3852294862,
      "currency_symbol": "$",
      "details": "",
      "last_invoice_kind": null
    }
  },
  {
    "client": {
      "id": XXXXXXXX,
      "name": "Test Client 2",
      "active": true,
      "currency": "Euro - EUR",
      "highrise_id": null,
      "updated_at": "2016-12-07T11:30:52Z",
      "created_at": "2016-12-07T11:30:52Z",
      "statement_key": "0e89949a5f3a8ff8ce04fc4fe35450a8",
      "default_invoice_kind": null,
      "default_invoice_timeframe": null,
      "address": null,
      "cache_version": 2551533894,
      "currency_symbol": "€",
      "details": null,
      "last_invoice_kind": null
    }
  },
  {
    "client": {
      "id": XXXXXXXX,
      "name": "Test Client 3",
      "active": true,
      "currency": "Australian Dollar - AUD",
      "highrise_id": null,
      "updated_at": "2016-12-07T22:18:01Z",
      "created_at": "2016-12-07T11:32:46Z",
      "statement_key": "b6c64fb061d967d6055da58c9ee8e266",
      "default_invoice_kind": null,
      "default_invoice_timeframe": null,
      "address": "",
      "cache_version": 3049235833,
      "currency_symbol": "$",
      "details": "",
      "last_invoice_kind": null
    }
  }
]`

**Comment by gavinbenda** [comment]
Looks like they've changed it from _Australia Dollar - AUD_ to _Australian Dollar - AUD_

**Comment by ithielnor** [comment]
I've committed a fix for #41. I'll release a new build in a few minutes.
