### ISSUE TITLE
.ListExpenses() returning empty list

### ISSUE THREAD

**Issue by zzzaJ** [ithielnor/harvest.net#65]
When I run the following code:

HarvestRestClient hclient= new HarvestRestClient("subdomain", "name@domain.com", "password");
var expenses = hclient.ListExpenses();

The expenses variable contains an empty list, however there are expense records when checked on the website. When looking at the Harvest API official documentation there is no way to view all expenses, thus I just want to ask if there is a way to do this through the wrapper.

**Comment by ithielnor** [comment]
IIRC the API used to have an unofficial/partial expenses resource. They may have removed it, in which case we're out of luck there.
