### ISSUE TITLE
Weekly Capacity not returned by ListUsers

### ISSUE THREAD

**Issue by daniariesan** [ithielnor/harvest.net#68]
User model doesn't have a property to read the WeeklyCapacity. Please let us know if this is part of another object. Thanks

See below json we got from harvest /people API call:
"user": {
      "id": 885498,
      "email": "test@aaa.com",
      "created_at": "2014-12-12T16:18:54Z",
      "is_admin": false,
      "first_name": "test",
      "last_name": "test",
      "timezone": "Kyiv",
      "is_contractor": false,
      "telephone": "",
      "is_active": true,
      "has_access_to_all_future_projects": false,
      "default_hourly_rate": 0,
      "department": "(Ukraine) QA",
      "wants_newsletter": false,
      "updated_at": "2017-02-06T11:20:32Z",
      "cost_rate": null,
      **"weekly_capacity": 144000**
    }

**Comment by ithielnor** [comment]
This is a new field that isn't yet documented in their API. I'll add it, but it may yet change.
