### ISSUE TITLE
Listing invoice with only "from" parameter returns incorrect results

### ISSUE THREAD

**Issue by pharrukh** [ithielnor/harvest.net#70]
It might be a mistake of Harvest API but it exists. When passing only "from" parameter, resulting invoices are of dates that are earlier then "from" date.

I prepared a PR with fix: https://github.com/pharrukh/harvest.net/pull/1

**Comment by ithielnor** [comment]
Hi Pharrukh,

I'm not sure I agree with the implementation. You're essentially injecting extra search parameters that the user did not request to work around a bug in Harvest's API. I'd rather let the user decide how they want to do that until such time as Harvest fixes the problem.
